name: Clue Society
favicon: null
layout_spectrum: 0.31
typography_spectrum: 0.8786037729587406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8604428374674171
  lightness: 0.843187345424667
  saturation: 0.767178843030706
  rhythmicContrast: 0.6619348521344364
purpose: []
